### PR TITLE
Add no-std version of humidity calculations

### LINKED ISSUE #39: Humidity functions for no-std
Feature proposal
----------------------

Provide calculation of dew-point from relative humidity for no_std using a compensated rule-of-thumb formula that provides reasonable accuracy within the range 50% <= RH <= 100% and 0° < t < 30°C. Provide accuracy caveats in the documentation.

This will mean that users of the humidity module will obtain different results depending whether they are running std or no_std.

Remove the  #[cfg(not(feature = "no_std"))] restriction on fn as_absolute_humidity() and fn as_vapor_pressure(), since these functions are linear and are supported by no_std.

Discussion
--------------
The new humidity module does not provide humidity, dew-point and vapor pressure calculations for no_std. Embedded systems often use sensors that detect temperature and relative humidity (RH). It is reasonable to expect to be able to convert relative humidity to dew-point (td).

Humidity calculations are non-linear, and approximation formulas of reasonable accuracy rely on functions such as f64.ln() and f64.exp(), which are not available on no_std. 

However, for RH > 50% the relationship becomes nearly linear, and a compromise to provide some features for no_std is possible.

So that raises the question, how accurate do calculations need to be? For example, there is a common rule of thumb for relatively moist air:

td = t - ((100 - RH) / 5).

This can be calculated under no_std, and would provide accuracy to better than +/- 1°C for td or +/- 5% for RH for most of the range 0° < t < 30°C and 50% < RH < 100%. 

A more accurate variation on this formula includes compensation terms,  with coefficients chosen to minimize the root-mean-square error for 40% < RH < 100% and 0° < t <30°C (while insisting that the intercept at RH = 100% is td = t):

 td = t - ((100 - RH) / 5)* ((273.15 + t)/300)^2 - 0.00135*(RH-84.0)^2 + 0.35

The maximum error in td of this equation is +/- 0.3°C over the whole range of 50% <= RH <= 100% and 0° < t < 30°C.

The inverse function: from_dewpoint() for no_std is unavailable, since no_std does not provide square roots.  However, the basic rule-of-thumb could be used  td = t - ((100 - RH) / 5) to provide from_dewpoint() for no_std, but with lower accuracy.

### PR DESCRIPTION
**Pull request by eldruin**
Fixes #39

### CODE REVIEW

**Comment by eldruin** [comment]
@pukeko37 This PR solves issue #39. The tests also pass. Do you have any other concerns?

**Comment by pukeko37** [comment]
Also the function docs need a line added that they panic when fed invalid parameters.

    `/// Panics when percent outside the range 0.0 .. 100.0`
    `pub fn from_percent(percent: f64) -> Self {`

    `/// Panics when percent outside the range 0.0 .. 1.0`
    `pub fn from_ratio(relative_humidity: f64) -> Self {`

    `/// standard atmospheric pressure.`
    `/// Panics if dewpoint > temperature`
    `pub fn from_dewpoint(dewpoint: Temperature, temp: Temperature) -> Humidity {`

As an aside, I've been thinking of writing up a comment in the docs to indicate accuracy of the calculation algorithm. The accuracy depends on humidity and temperature and minimizes error for 0<t<30 deg C, and 50%< RH <= 100%. The error increases outside this range. It will take a bit of working out from me, but when I'm done I'll make doc changes and submit a PR.

**Comment by eldruin** [comment]
The Rust way would be to return `Result` in the functions with an error if the input parameters are invalid. However, looking at the rest of the library, none of these checks are performed so it would make this module a bit of an outlier.
So I ask myself, other than returning nonsensical values for out-of-range inputs there is no other problem in these calculations, right?
It would be similar to doing something like `Resistance::from_ohm(-100)`

**Comment by pukeko37** [comment]
Yes that's right. I think an assert is the best solution, given the circumstances.

Result, Option, NAN, they all add surplus baggage for the library users.

**Comment by pukeko37** [comment]
A more functional language, like Haskell with type constructors, would prevent users from creating a type containing nonsensical values in the first place. Sadly that's not easy with rust. Perhaps we could do something similar by creating a newtype for percent values, and wrapping them in assessor functions, and put the creation of percent objects in the user's domain.

**Comment by eldruin** [comment]
I am not sure about how you would circumvent having to return a `Result` somewhere with a newtype but feel free to suggest something.
An `assert!` will panic at runtime. To me that is worse than a `Result` despite the boilerplate and also invalidates doing things like [panic-never](https://crates.io/crates/panic-never), [no-panic](https://crates.io/crates/no-panic), or generally ensuring code does not panic.
This library does not panic anywhere either.

At the moment I rather favor keeping this as-is, since it is how the whole library works, and given that there is no other danger than, as the saying goes, "_garbage-in, garbage-out_"
Maybe we can discuss how to introduce input data validation for the library as a whole in a separate issue.

**Comment by pukeko37** [comment]
Yes, its a bit of a philosophical debate. Ok, for now I agree, lets go with what we've got. That's the pragmatic solution.

I'll have a bit of a think. I'm not getting a feeling there is a perfect solution here though.

**Comment by pukeko37** [comment]
> Maybe we can discuss how to introduce input data validation for the library as a whole in a separate issue.

Yes. There's a lot to talk about. I've looked through all the modules. Other than humidity, temperature could benefit from input validation (Temperatures < absolute zero). Perhaps speed ( > c).

**Pull request merged**
